### ISSUE TITLE
Add description in README files to the tree

### ISSUE THREAD

**Issue by jankapunkt** [mistermicheels/markdown-notes-tree#1]
This tool is exactly what I was going to write but you saved my day :rocket: 

However I have a feature request I'd like to discuss with you. I want to add a short paragraph of text below the folder title in a folder's README in order to place it in the parent (up until root) folder's tree as a description to the folder.

The idea behind this is to provide a detailed overview to new developers to one of our repositories with a large and complex folder structure.

Example:

A README.md in a subfolder of a folder:

---
# subfolder

this is a short description

* subsubfolder
---

generating the following tree for the parent folder

---
# parent folder name

* **subfolder** - this is a short description
  * **subsubfolder**
---

or for longer paragraphs

---
# parent folder name

* **subfolder**
  this is a short description
  * **subsubfolder**
---

I would be willing to prove a PR if you consider this to be a viable feature. What do you think?

**Comment by mistermicheels** [comment]
Hi there! Glad to hear that you like the tool :)

Your feature request sounds pretty sensible to me. Currently, the tool
either completely overwrites or ignores subfolder README files, so there
are some things to consider here:
- Does the user need to run the tool at least once before the description
can be added?
- How are we going to mark that description inside the file? (right now we
are using HTML comments to mark these kinds of things)
- How would the new code react to subfolder README files that have been
generated by the old code?

A PR for this would be very welcome! Note that for this kind of feature I
would like at least one additional integration test with corresponding test
data.

If anything in the current code is confusing, just let me know and I’ll try
to help.

**Comment by mistermicheels** [comment]
@jankapunkt did you already start that PR implementation? If not, I can also give it a go tomorrow or during the weekend.

**Comment by mistermicheels** [comment]
@jankapunkt I think the commit I just made will cover your use case.

See https://github.com/mistermicheels/markdown-notes-tree/tree/master/test-data/subdirectory-description/expected for an example result. 

By default, it behaves as in your first proposal. There is also a new command line argument `subdirectoryDescriptionOnNewLine` that makes it behave like your second proposal (see https://github.com/mistermicheels/markdown-notes-tree/tree/master/test-data/subdirectory-description-on-new-line/expected).

If this works for you, I will release a new version so you can easily integrate it. You can already play with the current code by checking out the repo and following the instructions at the bottom of the README.

**Comment by jankapunkt** [comment]
@mistermicheels wow that was fast :+1: both examples are really promising! If you would release them in a new version I would be very happy.

I could in returns promote your package with a short article on dev.to - just let me know if this is okay for you.

**Comment by mistermicheels** [comment]
@jankapunkt version 1.8.0 including this feature is now published to npm!

An article on dev.to would be really cool, so definitely feel free to do that 👍
