### ISSUE TITLE
fails catastrophically if a title is not found

### ISSUE THREAD

**Issue by gillyspy** [mistermicheels/markdown-notes-tree#11]
some of my markdown is generated by jsdoc2md and that can fail and create an empty file.  

Regardless of the reason for the empty file it causes mardown-notes-tree to bail. 
`Error: No title found for Markdown file ...`

It would be nice if:
- it didn't fail on these cases (>= skip behaviour would be acceptable)
- there was a way to have a default title that would be applied

ideas:
- perhaps the filename could be used?
- or maybe an entry for the file gets created but no link is generated? 

for now i'll try to stop the empty file from being created but i still see this failing behaviour as too heavy a hammer

**Comment by gillyspy** [comment]
for those using jsdoc2md i worked around this by looking for `/(^|[^#])[#][^#]/` title and if there wasn't one i prepended it based on the current stream chunk's filename.

but i would still like the above to play nicer

**Comment by mistermicheels** [comment]
Hi @gillyspy, thanks for reaching out!

The error on missing title is intended behavior to prevent users from forgetting to specify a proper title.

However, to cover your use case, I could add two additional flags:

- `ingoreEmptyFiles`: Don't throw error on empty files but completely ignore them
- `allowMissingTitle`: Don't throw error on missing title but instead use the file name as fallback

What do you think?

**Comment by gillyspy** [comment]
personally I would prefer `allowMissingTitle` fallback option.  Thanks!

**Comment by mistermicheels** [comment]
@gillyspy I released a beta version [1.13.0-beta.0](https://www.npmjs.com/package/markdown-notes-tree/v/1.13.0-beta.0) that includes the `allowMissingTitle` option. Can you let me know if this works on your end?

**Comment by gillyspy** [comment]
And this one is good also!
