### ISSUE TITLE
add configuration for number of spaces?

### ISSUE THREAD

**Issue by ahgraber** [mistermicheels/markdown-notes-tree#8]
I use a standard indent of 2 spaces for my markdown files; the automatic 4-space indent of `markdown-notes-tree` breaks my linting and prettier hooks.  Would it be possible to add a configuration option to set number of spaces?

**Comment by ahgraber** [comment]
I should note that part of the problem for me was the overlapping scope of which formatters/linters I had reviewing markdown documents.  
`prettier` and `markdownlint` as pre-commit hooks _plus_ `prettier`'s autoformat hook in VSCode is too much - (i.e., misconfiguration on my end)

This would be a nice improvement, but it's not an enhancement that would be required for my use.

**Comment by mistermicheels** [comment]
@ahgraber I published a version 1.12.0-beta.0 containing a `--numberSpaces` option to specify the number of spaces.

Please let me know if this is what you had in mind and how soon you'd need this published as a non-beta version.

**Comment by ahgraber** [comment]
This works perfectly with my other configuration - thank you!

As the beta version works for me, there's no inherent rush to publish a non-beta version - do so at your convenience.

Thanks for your efforts!

**Comment by mistermicheels** [comment]
@ahgraber FYI, I released a new version v1.12.0 which includes this and the pre-commit support.
